fix: harden NSS Wi-Fi pbuf setup

diff --git a/package/kernel/mac80211/files/qca-nss-pbuf.init b/package/kernel/mac80211/files/qca-nss-pbuf.init
--- a/package/kernel/mac80211/files/qca-nss-pbuf.init
+++ b/package/kernel/mac80211/files/qca-nss-pbuf.init
@@ -20,7 +20,7 @@ NAME=qca-nss-pbuf
 reload_wifi() {
   if [ -r /sys/module/ath11k/parameters/nss_offload ]; then
     nss_offload=$(cat /sys/module/ath11k/parameters/nss_offload 2> /dev/null)
-    [ "$nss_offload" -eq 1 ] && wifi up
+    [ "$nss_offload" = 1 ] && wifi up
   fi
 }
 
@@ -30,25 +30,45 @@ get_num_cpus() {
   echo "${num_cpus:-1}"
 }
 
+write_sysctl() {
+  local name="$1" value="$2" file
+
+  file="/proc/sys/${name//./\/}"
+  [ -w "$file" ] || {
+    logger -t "$NAME" -p user.debug "Skipping unavailable sysctl $name"
+    return 0
+  }
+
+  if ! printf '%s\n' "$value" > "$file"; then
+    logger -t "$NAME" -p user.warn "Failed to set sysctl $name=$value"
+  fi
+}
+
 apply_sysctl() {
-  [ "$(sysctl -n -e dev.nss.general.redirect)" -eq 0 ] && /etc/init.d/qca-nss-ecm start
+  local redirect
+
+  if [ -r /proc/sys/dev/nss/general/redirect ]; then
+    redirect=$(cat /proc/sys/dev/nss/general/redirect 2> /dev/null)
+    [ "$redirect" = 0 ] && /etc/init.d/qca-nss-ecm start
+  fi
 
   # Running this script multiple times is useless, as extra_pbuf_core0
   # can't be changed if it is allocated, assume it's already been run.
-  if [ "$(sysctl -n -e dev.nss.n2hcfg.extra_pbuf_core0)" -eq 0 ]; then
+  extra_pbuf=$(sysctl -n -e dev.nss.n2hcfg.extra_pbuf_core0 2> /dev/null)
+  if [ "$extra_pbuf" = 0 ] || [ -z "$extra_pbuf" ]; then
     logger -t $NAME "$board - setting dev.nss.n2hcfg.extra_pbuf_core0=$extra_pbuf_core0"
-    sysctl -w dev.nss.n2hcfg.extra_pbuf_core0="$extra_pbuf_core0" > /dev/null 2>&1
+    write_sysctl dev.nss.n2hcfg.extra_pbuf_core0 "$extra_pbuf_core0"
   else
     logger -t $NAME "Sysctl key 'extra_pbuf_core0' already set to '""$extra_pbuf_core0""'. Skipping applying wifi nss configs"
   fi
 
-  sysctl -w dev.nss.n2hcfg.n2h_high_water_core0="$n2h_high_water_core0" > /dev/null 2>&1
+  write_sysctl dev.nss.n2hcfg.n2h_high_water_core0 "$n2h_high_water_core0"
 
   logger -t $NAME "$board - setting dev.nss.n2hcfg.n2h_wifi_pool_buf=$n2h_wifi_pool_buf"
-  sysctl -w dev.nss.n2hcfg.n2h_wifi_pool_buf="$n2h_wifi_pool_buf" > /dev/null 2>&1
+  write_sysctl dev.nss.n2hcfg.n2h_wifi_pool_buf "$n2h_wifi_pool_buf"
 
   logger -t $NAME "$board - setting dev.nss.n2hcfg.n2h_high_water_core0=$n2h_high_water_core0"
-  sysctl -w dev.nss.n2hcfg.n2h_high_water_core0="$n2h_high_water_core0" > /dev/null 2>&1
+  write_sysctl dev.nss.n2hcfg.n2h_high_water_core0 "$n2h_high_water_core0"
 
 }
 
@@ -63,7 +83,7 @@ apply_nss_config() {
 
   enable_nss_offload=$(cat /sys/module/ath11k/parameters/nss_offload)
 
-  if [ "$enable_nss_offload" -ne "1" ]; then
+  if [ "$enable_nss_offload" != "1" ]; then
     logger -t $NAME -s user.warn "Module parameter 'nss_offload=0'. Skipping applying wifi nss configs"
     exit 1
   fi
@@ -78,10 +98,10 @@ apply_nss_config() {
   config_get n2h_queue_limit_core0 opt n2h_queue_limit_core0 256
   config_get n2h_queue_limit_core1 opt n2h_queue_limit_core1 256
 
-  sysctl -w dev.nss.clock.auto_scale="$auto_scale" > /dev/null 2>&1
+  write_sysctl dev.nss.clock.auto_scale "$auto_scale"
 
-  sysctl -w dev.nss.n2hcfg.n2h_queue_limit_core0="$n2h_queue_limit_core0" > /dev/null 2>&1
-  sysctl -w dev.nss.n2hcfg.n2h_queue_limit_core1="$n2h_queue_limit_core1" > /dev/null 2>&1
+  write_sysctl dev.nss.n2hcfg.n2h_queue_limit_core0 "$n2h_queue_limit_core0"
+  write_sysctl dev.nss.n2hcfg.n2h_queue_limit_core1 "$n2h_queue_limit_core1"
 
   local memory_profile memtotal board
   board=$(board_name)
@@ -133,6 +153,8 @@ set_stats_disable() {
   config_load pbuf
   config_get stats_disable opt stats_disable 1
 
+  [ -d /sys/kernel/debug/ath11k ] || return 0
+
   find /sys/kernel/debug/ath11k -name stats_disable | while read -r stats_file; do
     stats_msg_prefix="Disabling"
     [ "$stats_disable" -eq 0 ] && stats_msg_prefix="Enabling"
@@ -156,15 +178,18 @@ set_scaling_governor() {
   fi
 
   if [ -n "$scaling_available_governors" ] && [ -n "$scaling_governor" ]; then
-    if [[ "$scaling_available_governors" =~ $scaling_governor ]]; then
+    case " $scaling_available_governors " in
+      *" $scaling_governor "*)
       logger -t $NAME -p user.notice "Setting CPU scaling governor to '$scaling_governor'"
       num_cpus=$(get_num_cpus)
       for num in $(seq 0 $((num_cpus - 1))); do
         echo "$scaling_governor" > "/sys/devices/system/cpu/cpu${num}/cpufreq/scaling_governor"
       done
-    else
+      ;;
+      *)
       logger -t $NAME -p user.error "'$scaling_governor' not available in CPU governors [ $scaling_available_governors ]"
-    fi
+      ;;
+    esac
   fi
 }
 
@@ -176,7 +201,7 @@ start() {
 
   num_cpus=$(get_num_cpus)
   hash_bitmap="$(((1 << num_cpus) - 1))"
-  sysctl -w dev.nss.rps.hash_bitmap=$hash_bitmap > /dev/null 2>&1
+  write_sysctl dev.nss.rps.hash_bitmap "$hash_bitmap"
   reload_wifi
 
 }
